version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3002:3002"
